import { Inter } from "next/font/google";
import { MenuProvider } from "./contexts/MenuContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<MenuProvider>
				<body className={inter.className}>{children}</body>
			</MenuProvider>
		</html>
	);
}
